### ISSUE TITLE
Run HttpServer fail issue

### ISSUE THREAD

**Issue by michaelii** [mitls/mitls-flex#6]
I got the situation here. I want to try to run the sample HTTP server.
I execute the command

```
/Flexapps.exe -s fh --accept 127.0.0.1:4433 --server-cert mitls
```

I got the error here

```
System.Exception: Error at Handshake_full_RSA.fs:141: Private key not found for the given CN: mitls.
```

I do not change any code just want to run a sample.
I try to trace the code. It looks like cannot read any file of RSA private key.
Can you assist me to resolve it?

Thanks

Michael

**Comment by sishtiaq** [comment]
Hi Michael, 
mitls-flex has gone unsupported while we work on mitls-fstar. There is a plan to port the old apps over to mitls-fstar, but that won't be done for a while yet.

**Comment by s-zanella** [comment]
I couldn't reproduce the error, this works for me:

```
$ mono flex/FlexApps/bin/Release/FlexApps.exe -s fh --accept 127.0.0.1:4443 --server-cert mitls
--- TCP : Listening on 127.0.0.1:4443
--- TCP : Accepting as rsa.cert-01.mitls.org
--- --- Client accepted
--- # CLIENT HELLO : FlexClientHello.receive
```

Did you follow the instructions in https://github.com/mitls/mitls-flex#4-certificates-and-parameters to import tests certificates and keys into your certificate store?

**Comment by sishtiaq** [comment]
Santiago makes a good point. That section, though, is written a bit backwards: just do the "make pki.built" step and ignore the text before it.

**Comment by michaelii** [comment]
Thank you for your support. I am try to do the research on this field. It is very helpful.
Previous time, I try to execute "make pki.buit" fail. I do not notice. And Everything is good.
However, I have further more question about "attack scenario"
e.g.
FlexApps.exe -s wal --accept 127.0.0.1:4433 --server-cert mitls

error message:
 System.Exception: Error at FlexRecord.fs:85: Error at TLSConstants.fs:950: Unknown content type.

Do you have any sample scenario attack command for local testing? or I miss something need to install? Thank you for your help.

Thanks

Michael

**Comment by sishtiaq** [comment]
Hi Michaelii,
Can you tell us what steps you're taking before you get this error? Are you doing all the steps listed in 
https://github.com/mitls/mitls-flex#5-flextls? If you can grab a screenshot of your terminal with all the steps and the error, that would help in debugging your issue.

**Comment by s-zanella** [comment]
The "Warning alert" scenario that you're trying to run can only be run as a client, so the options `--accept 127.0.0.1:4433 --server-cert mitls` are not needed and are in fact ignored.

If you wanted to run it against a server listening on 127.0.0.1:4433, you'd use:

`FlexApps.exe -s wal --connect 127.0.0.1:4433`

This is what you'd get when run against an up to date version of OpenSSL (not vulnerable):

```
MacBook-Pro:mitls-flex anonymous$ mono flex/FlexApps/bin/Release/FlexApps.exe -s wal --connect 127.0.0.1:4443 
--- TCP : Connecting to 127.0.0.1:4443
--- --- Done
--- # CLIENT HELLO : FlexClientHello.send
--- --- Payload : "0100004A0303580DC9E1F092FD9BC6D56BB764783FD6B84734B286A2ACA3B5456C5336265FFF000002009C0100001F000B00020100000A00080006001700180019BB8F000000170000FF01000100"
--- --- Protocol Version : TLS_1p2
--- --- Sid : 
--- --- Client Random : 580DC9E1F092FD9BC6D56BB764783FD6B84734B286A2ACA3B5456C5336265FFF
--- --- Ciphersuites : [TLS_RSA_WITH_AES_128_GCM_SHA256]
--- --- Compressions : [NullCompression]
--- --- Extensions : [TLSExtensions+clientExtension+CE_ec_point_format;
 TLSExtensions+clientExtension+CE_ec_curves; TLSExtensions+clientExtension;
 TLSExtensions+clientExtension;
 TLSExtensions+clientExtension+CE_renegotiation_info]
--- # SERVER HELLO : FlexServerHello.receive

Unhandled Exception:
System.Exception: Error at FlexHandshake.fs:78: Unexpected content type : Alert
 Payload (2 Bytes) : 0228.
```

A more interesting attack to try out is [SKIP](https://mitls.org/pages/attacks/SMACK#skip). Here are the detailed steps you need to reproduce it on Windows:

```
- Download and install jdk-8-windows-x64.exe from http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html
This version is vulnerable to SKIP

- Download and install e.g. jre-8u71-windows-x64 from http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html
This version is patched for SKIP

- In a bash terminal, set
$ alias java-1.8.0="/cygdrive/c/Program\ Files/Java/jdk1.8.0/jre/bin/java.exe"
$ alias javac="/cygdrive/c/Program\ Files/Java/jdk1.8.0/bin/javac.exe"

- From ~/mitls-flex/flex/FlexApps/
$ javac client.java

- Check that with a vulnerable version, we get www.google.com webpage (from ~/mitls-flex/flex/FlexApps/)
$ java-1.8.0 client https://www.google.com
<html>...

- In a PowerShell as admin,
> echo '127.0.0.1 www.google.com' > .\drivers\etc\hosts

- Start flexTLS server attacker, from folder with google.com chain: ~/mitls-flex/tests/pki/rsa/certificates
$ ~/mitls-flex/flex/FlexApps/bin/Release/FlexApps.exe -s efin --accept 127.0.0.1

- Run Java client using vulnerable JRE (from ~/mitls-flex/flex/FlexApps/)
$ java-1.8.0 client https://www.google.com
You are vulnerable to the EarlyFinished attack!

- Check that the patched version is not vulnerable
$ java client
Exception in thread "main" javax.net.ssl.SSLHandshakeException: Received Finished message before ChangeCipherSpec
...

- Reset hosts file from PowerShell as admin
> echo '#127.0.0.1 www.google.com' > .\drivers\etc\hosts
```

**Comment by michaelii** [comment]
Dear all

Thank you for your suggestion. I follow your scenario and currently has no more issue.
Please close the issue. Thanks

I will try to dig in this tool and refer this paper in my research. I will keep update the issue to here

Thanks

Michael
